"""ss

Revision ID: ac749de9a8ef
Revises: 6d3d076f332a
Create Date: 2023-10-29 15:48:29.495020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac749de9a8ef'
down_revision = '6d3d076f332a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_text', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_text', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
